apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantumfpo-java-backend
  namespace: quantumfpo
  labels:
    app: quantumfpo-java-backend
    version: v0.0.1-alpha
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quantumfpo-java-backend
  template:
    metadata:
      labels:
        app: quantumfpo-java-backend
        version: v0.0.1-alpha
    spec:
      containers:
      - name: java-backend
        image: JAVA_BACKEND_IMAGE
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: quantumfpo-config
              key: SPRING_PROFILES_ACTIVE
        - name: JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: quantumfpo-config
              key: JAVA_OPTS
        - name: PYTHON_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: quantumfpo-config
              key: PYTHON_API_BASE_URL
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: quantumfpo-java-backend
  namespace: quantumfpo
  labels:
    app: quantumfpo-java-backend
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: quantumfpo-java-backend
---