apiVersion: v1
kind: ServiceMonitor
metadata:
  name: quantumfpo-monitoring
  namespace: quantumfpo
  labels:
    app: quantumfpo
spec:
  selector:
    matchLabels:
      app: quantumfpo-java-backend
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s
---
apiVersion: v1
kind: ServiceMonitor  
metadata:
  name: quantumfpo-python-monitoring
  namespace: quantumfpo
  labels:
    app: quantumfpo
spec:
  selector:
    matchLabels:
      app: quantumfpo-python-backend
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: quantumfpo-network-policy
  namespace: quantumfpo
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: quantumfpo
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: quantumfpo
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 8002
    - protocol: TCP
      port: 80
  egress:
  - {}  # Allow all egress traffic
---