apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantumfpo-python-backend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quantumfpo-python-backend
  template:
    metadata:
      labels:
        app: quantumfpo-python-backend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: python-backend
        image: ghcr.io/lxtececo/quantumfpo-python-backend:fa0749cc4d837f1c1ad0a61ee437138bbda69459
        ports:
        - containerPort: 8002
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "512Mi"
            cpu: "250m"
            ephemeral-storage: "2Gi"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: tmp-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: quantumfpo-python-backend
  namespace: dev
spec:
  type: ClusterIP
  ports:
  - port: 8002
    targetPort: 8002
  selector:
    app: quantumfpo-python-backend

