# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven (Standalone)

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - 'backend/src/main/java/**'
      - 'backend/src/test/java/**'
      - 'backend/pom.xml'
      - '.github/workflows/maven.yml'
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - 'backend/src/main/java/**'
      - 'backend/src/test/java/**'
      - 'backend/pom.xml'
      - '.github/workflows/maven.yml'
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Run tests with Maven
      run: |
        cd backend
        mvn clean test -B

    - name: Build with Maven
      run: |
        cd backend
        mvn -B package -DskipTests

    - name: Generate test reports
      if: always()
      run: |
        cd backend
        mvn surefire-report:report-only
        mvn jacoco:report

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: java-maven-test-results
        path: |
          backend/target/surefire-reports/
          backend/target/site/

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/target/site/jacoco/jacoco.xml
        flags: java-maven
        name: java-maven-coverage
        fail_ci_if_error: false

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
      #uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
