# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI (Standalone)

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/node.js.yml'
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/node.js.yml'
  workflow_dispatch:  # Manual trigger

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
        
    - name: Change to frontend directory and install dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Lint frontend code
      run: |
        cd frontend
        npm run lint
      continue-on-error: true
        
    - name: Test frontend with coverage
      run: |
        cd frontend
        npm test -- --coverage --watchAll=false
        
    - name: Build frontend
      run: |
        cd frontend
        npm run build --if-present

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./frontend/coverage/lcov.info
        flags: frontend-standalone
        name: frontend-standalone-coverage
        fail_ci_if_error: false

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: frontend-test-results-${{ matrix.node-version }}
        path: |
          frontend/coverage/
          frontend/dist/
